package com.austin.sciencelab.navigation

const val ROUT_HOME="home"
const val ROUT_ABOUT="about"
const val ROUT_SPLASH="splash"
const val ROUT_SCIENCE1="science1"
const val ROUT_SCIENCE2="science2"
const val ROUT_VIRTUALLABS1="virtuallabs1"
const val ROUT_VIRTUALLABS2="virtuallabs2"
const val ROUT_VIRTUALLABS3="virtuallabs3"
const val ROUT_QUALITATIVE="qualitative"
const val ROUT_QUANTITATIVE="quantitative"
const val ROUT_MOLES="moles"
const val ROUT_ORGANIC="organic"
const val ROUT_ORGANICANALYSIS="organicanalysis"
const val ROUT_COMPOUNDS="compounds"
const val ROUT_INORGANIC="inorganic"
const val ROUT_CATION="cation"
const val ROUT_SOLUBILITY="solubility"
const val ROUT_ENERGYCHANGES="energychanges"
const val ROUT_REACTION="reaction"
const val ROUT_REACTIONRATES="reactionrates"
const val ROUT_ENERGY="energy"
const val ROUT_MECHANICS="mechanics"
const val ROUT_PRACTICALS="practicals"
const val ROUT_GEOMETRICOPTICS="geometricoptics"
const val ROUT_ELECTRICITY="electricity"
const val ROUT_THERMODYNAMICS="thermodynamics"
const val ROUT_WAVES="waves"
const val ROUT_OPTICS="optics"
const val ROUT_ELECTRICITYANDMAGNETISM="electricityandmagnetism"
const val ROUT_CELLBIOLOGY="cellbiology"
const val ROUT_CELLPHYSIOLOGY="cellphysiology"
const val ROUT_CELLPHYSIO="cellphysio"
const val ROUT_GENETICS="genetics"
const val ROUT_MOVEMENT="movement"
const val ROUT_PLANTANATOMY="plantanatomy"
const val ROUT_SLIDES="slides"
const val ROUT_TEMPORARY="temporary"
const val ROUT_CELLBIO="cellbio"
const val ROUT_PRACTICAL="practical"
const val ROUT_MICROBIOLOGY="microbiology"
const val ROUT_UPLOADQUESTIONS="uploadquestions"
const val ROUT_VIEWQUESTIONS="viewquestions"

//Auth

const val ROUT_REGISTER= "register"
const val ROUT_LOGIN= "login"

